### ISSUE TITLE
No Email is sent during a REMOVE all when the user doesn't exist in a azure:dev1 environment

### ISSUE THREAD

**Issue by gkeir** [Signiant/External-user-provisioning#8]
I ran the user provisioning tool to remove a user. The application return the following error and failed to send and email. The output is as follows...
Real username subsituted

python3 -m project.user_provision -n "User Name" -c "project/config.yaml" -e username@blah.com -r all

Running remove: papertrail:dev  
papertrail:dev username@blah.com does not exist, delete failed

Running remove: papertrail:prod  
papertrail:prod username@blah.com does not exist, delete failed

Running remove: bitbucket:prod  
The user username does not exist, delete failed

Running remove: slack:prod  
username has NOT been removed, remove manually from the signiant-dev Slack team.

Running remove: artifactory:prod  
username is remove along with AD account

Running remove: aws:dev1  
aws:dev1: User usernameprofile has been deleted

Running remove: aws:dev2  
aws:dev2: User usernameprofile has been deleted

Running remove: azure:dev1  
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gkeir/External-user-provisioning/project/user_provision.py", line 140, in <module>
    main()
  File "/Users/gkeir/External-user-provisioning/project/user_provision.py", line 86, in main
    if runPlugins(configMap, pluginsremove, email, allPermissions, pluginInstruction, availablePlugins, args.name, arg='remove'):
  File "/Users/gkeir/External-user-provisioning/project/user_provision.py", line 114, in runPlugins
    json = (plugin_handle.removeUser(email, configMap, allPermissions, plugin_tag))
  File "./project/plugins/azure/__init__.py", line 96, in removeUser
    return getJsonResponse("Azure Active Directory", email, log, instruction)
TypeError: getJsonResponse() missing 1 required positional argument: 'success'

**Comment by KseniaLL** [comment]
The issue is fixed
